### ISSUE TITLE
Live 11

### ISSUE THREAD

**Issue by tcbtcb** [Henry-White/Ableton-Live-11-Script_Launchkey_Mini_MK3#1]
Hello - this isn't an issue w/ your beatstep script, but a question. I've been trying to write a script for Live 11 (has to be 11) for one of my controllers and have had a horrible time. Mostly just bootstraping and improting things correclty which I dont' really understand for MIDI controllers. I'm decent w/ Python and the Live API but I'm having a terrible time getting started. I was hoping to get a paid working session with you, who clearly does understand this stuff, to get me off the ground. 

Thanks, and yes that's a pic I took of Scientest in a studio as my avatar, 

- TCB

**Comment by Henry-White** [comment]
Hello,
I'm sorry to disappointing you, but I'm really newbie in the Live API and even Python. I'm just a programmer with a lot of experience, so it gives me a quick sense of what I'm seeing. All I did on this project was solve a little problem that was bothering me, so... Sorry for that, but guess I will not be so useful for you.

**Comment by tcbtcb** [comment]
No worries, thanks for responding, obviously close the issue. I appreciate
it.
